apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
    app: node 
  name: liveness-tcp
spec:
  containers:
  - name: goproxy 
    image: docker.io/googlecontainer/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10 
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20 
